# Generated by Django 3.2.7 on 2023-03-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esg_reports',
            name='site',
            field=models.CharField(default='NULL', max_length=100, verbose_name='来源网站'),
        ),
    ]
