# Generated by Django 4.1.7 on 2023-03-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name'], name='login_user_name_31bd66_idx'),
        ),
    ]
